In [1]:
import numpy as np

In [2]:
pop = np.array([[1,0,0,0],[1,0,0,1],[0,0,0,0],[0,1,0,1],[0,0,1,1],[0,1,0,0],[1,0,0,1],[1,0,0,0],[1,1,1,1],[1,0,1,0]])
is_confined = np.array([True,True,True,True,False,True,True,False,False,True])
next_test_date = np.array([3,4,66,6,4,3,2,1,2,10])

hcw = np.array([1,3,4,6])

In [16]:
day = 9

In [ ]:
np.logical_and(np.logical_and(sample1[:,0]==0,is_conf==True), day>nex_tes)

In [11]:
print(pop)
print(is_confined)

[[1 0 0 0]
 [1 0 0 1]
 [0 0 0 0]
 [0 1 0 1]
 [0 0 1 1]
 [0 1 0 0]
 [1 0 0 1]
 [1 0 0 0]
 [1 1 1 1]
 [1 0 1 0]]
[ True  True  True  True False  True  True False False  True]


In [ ]:
hcw[np.logical_and(is_conf[hcw]==True,day>nex_tes[hcw])]

In [ ]:
is_conf[hcw]==True

In [17]:
hcw[np.logical_and(np.logical_and(is_confined[hcw]==False, day >= next_test_date[hcw] + 6),pop[hcw][:,0]==0)]

array([], dtype=int64)